### ISSUE TITLE
Issue with resource delete

### ISSUE THREAD

**Issue by jpeimer** [RedHatQE/openshift-python-wrapper#1678]
**Describe the bug**
Issue with resource delete

```
if self.exists:   <------- true at this point
     hashed_data = self.hash_resource_dict(resource_dict=self.instance.to_dict())    <------- resource was cleaned up at this point, so calling self.instance raises TimeoutExpiredError
```

Even if `instance` will return None instead of raising the TimeoutExpiredError, we'll still have a problem, because we can't call `to_dict()` on `None`

**Expected behavior**
delete() not raising an error even if the resource was cleaned up

**Comment by dbasunag** [comment]
@myakove / @rnetser The problem has more impact than delete(), now that TimeoutSampler always raises TimeoutExpiredError  https://github.com/RedHatQE/openshift-python-wrapper/pull/1379/files, and retry_cluster_exceptions() or any instance call raises the same, anywhere we use timeoutsampler with wrapper, would give us random TimeoutExpiredError and we can no longer utilize exceptions_dict to retry on these failures. We need to raise the actual exceptions instead of TimeoutExpiredError from TimeoutSampler.

**Comment by myakove** [comment]
Please make a PR and we will review it.
Thanks.
